### ISSUE TITLE
 no registered task type 'zephyr-tools'

### ISSUE THREAD

**Issue by hongshui3000** [circuitdojo/zephyr-tools#1]
When performing some tasks, such as serial port monitoring tasks

Zephyr Tools: Serial Monitor

vscode will output an error message
![image](https://user-images.githubusercontent.com/25566498/214998453-61202595-8cb0-4203-aaf1-1ec449508105.png)

**Comment by jaredwolff** [comment]
Hi @hongshui3000 

Did you run `Zephyr Tools: Setup`?

**Comment by hongshui3000** [comment]
yes，In fact, when running Zephyr Tools: Setup, the same error.Although an error is reported, it does not seem to affect the use
The error output is under the Tasks of OUTPUT.
![image](https://user-images.githubusercontent.com/25566498/215242391-f4f56d2a-bfaf-4a44-8fef-4127817ea491.png)
Seems to be an error generated by these codes below, I'm not sure
```
		exec = new vscode.ShellExecution(cmd, shellOptions);

		// Task
		task = new vscode.Task(
			{ type: "zephyr-tools", command: taskName },
			vscode.TaskScope.Workspace,
			taskName,
			"zephyr-tools",
			exec
		);

		// Start execution
		await TaskManager.push(task, {
			ignoreError: false, lastTask: true, successMessage: "Init complete!",
			callback: done, callbackData: { dest: dest }
		});
```

**Comment by jaredwolff** [comment]
Ok. Correct me if I'm wrong. The task is working but that error is coming over the output.

As long as it doesn't affect functionality I'll check it out at some point soon. Thanks for reporting.

**Comment by hongshui3000** [comment]
Thanks for open source such a good extension
