### ISSUE TITLE
Zephyr: Init repo doesn't work if ZEPHYR_BASE is already set.

### ISSUE THREAD

**Issue by mikaelj** [circuitdojo/zephyr-tools#11]
The tools should unset ZEPHYR_BASE before running west init.

**Comment by jaredwolff** [comment]
@mikaelj I need more information than "it doesn't work". Please provide logs or more context. 

Or if you already know the fix feel free to submit a PR.

**Comment by mikaelj** [comment]
@jaredwolff I can't submit a PR at the moment because I don't know how to create VSCode extensions (and thus can't test it), but the fix itself is to call "unset ZEPHYR_BASE" before doing anything with west.

I'll try to grab logs.

**Comment by jaredwolff** [comment]
Hi @mikaelj I'm going to close this. Feel free to re-open if you have more info.
