### ISSUE TITLE
v0.2.1/macOS: setup fails to download files, no output, completes with "everything fine" but no toolchain installed.

### ISSUE THREAD

**Issue by mikaelj** [circuitdojo/zephyr-tools#12]
"Error downloading zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz. Check output for more info."
"Error downloading zephyr-sdk-0.16.4_macos-aarch64_minimal.tar.xz. Check output for more info."

~/.zephyrtools:

    ~/.zephyrtools> ls -la
    total 0
    drwxr-xr-x    6 mikaelj  staff   192  5 Mar 14:02 .
    drwxr-xr-x@ 102 mikaelj  staff  3264  5 Mar 13:57 ..
    drwxr-xr-x    3 mikaelj  staff    96  5 Mar 13:58 cmake
    drwxr-xr-x    6 mikaelj  staff   192  5 Mar 13:58 downloads
    drwxr-xr-x    6 mikaelj  staff   192  5 Mar 13:58 env
    drwxr-xr-x    3 mikaelj  staff    96  5 Mar 13:58 newtmgr
     ~/.zephyrtools> ls -lah downloads/
    total 184992
    drwxr-xr-x  6 mikaelj  staff   192B  5 Mar 13:58 .
    drwxr-xr-x  6 mikaelj  staff   192B  5 Mar 14:02 ..
    -rw-r--r--  1 mikaelj  staff    67M  5 Mar 13:58 cmake-3.22.0-macos-universal.tar.gz
    -rw-r--r--  1 mikaelj  staff   8,5M  5 Mar 13:58 newtmgr.zip
    -rw-r--r--  1 mikaelj  staff   4,9K  5 Mar 13:57 zephyr-sdk-0.16.4_macos-aarch64_minimal.tar.xz
    -rw-r--r--  1 mikaelj  staff   295K  5 Mar 13:57 zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
    Pellefant [14:02] ~/.zephyrtools>

As you can see, no ~/.zephyrtools/toolchain directory.

VSCode Output Tab:

    [SETUP] Installing zephyr-sdk-0.16.4 (latest) toolchain...
    [SETUP] downloading https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_macos-aarch64_minimal.tar.xz
    [SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-aarch64-apple-darwin.tar.gz
    [SETUP] downloading https://docs.jaredwolff.com/files/newtmgr/darwin/newtmgr.zip
    [SETUP] unzip /Users/mikaelj/.zephyrtools/downloads/newtmgr.zip to /Users/mikaelj/.zephyrtools/newtmgr
    [SETUP] downloading https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0-macos-universal.tar.gz
    tar -xvf "/Users/mikaelj/.zephyrtools/downloads/cmake-3.22.0-macos-universal.tar.gz" -C "/Users/mikaelj/.zephyrtools/cmake"
    git version 2.42.0
    [SETUP] git installed
    python3 --version
    [SETUP] python3 found
    python3 -m pip --version
    pip 24.0 from /Users/mikaelj/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
    [SETUP] pip installed
    python3 -m venv --help
    [SETUP] python3 venv OK
    python3 -m venv "/Users/mikaelj/.zephyrtools/env"
    [SETUP] virtual python environment created
    Collecting west
      Using cached west-1.2.0-py3-none-any.whl (95 kB)
    Requirement already satisfied: setuptools in /Users/mikaelj/.zephyrtools/env/lib/python3.9/site-packages (from west) (58.0.4)
    Collecting pykwalify
      Using cached pykwalify-1.8.0-py2.py3-none-any.whl (24 kB)
    Collecting packaging
      Using cached packaging-23.2-py3-none-any.whl (53 kB)
    Collecting colorama
      Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
    Collecting PyYAML>=5.1
      Using cached PyYAML-6.0.1-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
    Collecting ruamel.yaml>=0.16.0
      Using cached ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
    Collecting python-dateutil>=2.8.0
      Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
    Collecting docopt>=0.6.2
      Using cached docopt-0.6.2.tar.gz (25 kB)
    Collecting six>=1.5
      Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
    Collecting ruamel.yaml.clib>=0.2.7
      Using cached ruamel.yaml.clib-0.2.8-cp39-cp39-macosx_12_0_arm64.whl (134 kB)
    Using legacy 'setup.py install' for docopt, since package 'wheel' is not installed.
    Installing collected packages: six, ruamel.yaml.clib, ruamel.yaml, python-dateutil, docopt, PyYAML, pykwalify, packaging, colorama, west
        Running setup.py install for docopt: started
        Running setup.py install for docopt: finished with status 'done'
    Successfully installed PyYAML-6.0.1 colorama-0.4.6 docopt-0.6.2 packaging-23.2 pykwalify-1.8.0 python-dateutil-2.9.0.post0 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 six-1.16.0 west-1.2.0
    [SETUP] west installed
    [SETUP] Zephyr setup complete!

Doesn't give any specific info.

**Comment by jaredwolff** [comment]
@mikaelj pushed version 0.2.2 which should address this. Thanks for reporting!
