### ISSUE TITLE
Checksum mismatch and 404 error during setup procedure

### ISSUE THREAD

**Issue by maxkraft7** [circuitdojo/zephyr-tools#14]
From the output of the setup procedure the following line:
```
[SETUP] downloading https://github.com/circuitdojo/zephyr-tools-cli/releases/download/0.1.7/zephyr-tools-0.1.7-x86_64-pc-windows-msvc.zip
```
results in the error [checksum mismatch](https://github.com/circuitdojo/zephyr-tools/blob/e1ffa256d74aa4c7e389c32ea0468fbb527a4665/src/extension.ts#L1746). 

The line 
```
[SETUP] downloading https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_windows-x86_64_minimal.zip
```
Results in a 404 error. Apparently the build artifact for windows now ends with .7z instead of .zip. Check the windows builds [here](https://github.com/zephyrproject-rtos/sdk-ng/releases/). And it doesn't even show the latest version available. 0.16.4 is the latest one offered to me even though 0.16.5 is already available. 

![grafik](https://github.com/circuitdojo/zephyr-tools/assets/49827312/8c39cc71-a0c5-42f3-b02f-e1b165721dc7)

**Comment by jaredwolff** [comment]
@maxkraft7 give 0.2.3 a shot.
[zephyr-tools-0.2.3.zip](https://github.com/circuitdojo/zephyr-tools/files/14499821/zephyr-tools-0.2.3.zip)

Also published to VSCode marketplace

**Comment by maxkraft7** [comment]
Now it works. Thanks! Got fixed very fast💯
