### ISSUE TITLE
Issue with Uninstall

### ISSUE THREAD

**Issue by Anand64** [circuitdojo/zephyr-tools#16]
Unable to uninstall the extension without **manually** uninstalling the other extensions **C/C++** and **Embedded Tools**

![image](https://github.com/circuitdojo/zephyr-tools/assets/43028204/cfd8965a-5b4a-4820-a9ed-c8cd6dafa337)

These extensions were already existing and I use them regularly.

**Comment by jaredwolff** [comment]
Hi @Anand64 

Seems more like a VSCode issue than the extension. Feel free to re-open if you have further comment.
