### ISSUE TITLE
Vscode git settings cause gitlens extensions to not work

### ISSUE THREAD

**Issue by hongshui3000** [circuitdojo/zephyr-tools#2]
Why are these settings needed?

```
		// Temporarily of course..
		let settings = {
			"git.enabled": false,
			"git.path": null,
			"git.autofetch": false
		};
```

**Comment by jaredwolff** [comment]
Hi @hongshui3000 

It interferes with `west` initially initializing a repository on Windows.

**Comment by hongshui3000** [comment]
> Hi @hongshui3000
> 
> It interferes with `west` initially initializing a repository on Windows.

Thanks Reply
