### ISSUE TITLE
"West" not found when attempting the "Create Project" command on Ubuntu

### ISSUE THREAD

**Issue by burke-david** [circuitdojo/zephyr-tools#21]
Trying to create a new Zephyr project using the extension command `Zephyr Tools: Create Project` but get the following error: `Command failed: west init -l /home/ahe/_code/zephyr_projects/z1/app /bin/sh: 1: west: not found`

OS: `Ubuntu 22.04.4`

git: `git version 2.34.1`

python3: `Python 3.10.12`

Zephyr SDK Variant: `Vanilla`

From within a VS Code terminal, `west` does seem to be installed:
```
$ west --version
West version: v1.2.0
```

**Comment by jaredwolff** [comment]
@burke-david interesting. Did you run `Zephyr Tools: Setup` first? I think there's a bug where you may have to run it twice especially if you just started fresh.

**Comment by burke-david** [comment]
No. I may have misunderstood the order of operations. I thought the `Zephyr Tools: Create Project` handled that. Running it now. Potentially of interest, before attempting to use your extension, I had run the steps in the [Getting Started Guide](https://docs.zephyrproject.org/latest/develop/getting_started/index.html) and was able to build and get the blinky binary loaded on my board.

**Comment by jaredwolff** [comment]
@burke-david sounds like you have setup the toolchain/SDK separately. The extension should do all of that for you. Nevertheless you should be on rails now to start using it!

**Comment by burke-david** [comment]
That was it. Closing the issue. Thanks for your help (and the extension!)
