### ISSUE TITLE
Change Zephyr SDK version

### ISSUE THREAD

**Issue by naNEQ** [circuitdojo/zephyr-tools#3]
Is there any easy way to update the Zephyr SDK version installed to the latest? I'm interested in the v0.16.0 in particular. I thought about downloading the SDK version I want and substituting the local folder in the .zephyrtools/toolchain. But I don't know if that alone would suffice and also how do you make sure that in the future I have the correct version installed (if for example I do a fresh installation on a new machine).

Similar to this is also how can I install additional toolchains, let's say for espressif processors.

**Comment by jaredwolff** [comment]
@naNEQ it's reliant on whatever is defined in the `west.yml` in the project you're pulling down. I'm not sure what you're referring to regarding version v0.16.0. Neither Zephyr or NCS have a version number like that.

**Comment by naNEQ** [comment]
@jaredwolff yes, I agree re: the Zephyr version. But I'm actually referring to the Zephyr SDK, which, if I'm not completely mistaken, is downloaded and setup with your Zephyr Tools extension (under the .zephyrtools/toolchain folder)! Right now the extension is hardwired to download and setup the version 0.15.1 of the SDK with only the toolchain for building ARM cores ("arm-zephyr-eabi"). I was hoping there is a good way to be able to pull a newer version of the SDK.

**Comment by jaredwolff** [comment]
@naNEQ I think you may be referring to the toolchain? Yep currently it targets only one version of the ARM toolchain. You're welcome to submit a PR to make it so an end user can select which one they want.

**Comment by naNEQ** [comment]
> @naNEQ I think you may be referring to the toolchain? Yep currently it targets only one version of the ARM toolchain. You're welcome to submit a PR to make it so an end user can select which one they want.

Exactly, yes! Thanks for answering!

**Comment by LokleLama** [comment]
there is a pull request that should help: https://github.com/circuitdojo/zephyr-tools/pull/7

**Comment by jaredwolff** [comment]
@naNEQ you can now select the toolchain you want during `Zephyr Tools: Setup` still looking to build this out a bit more but it should give you some more flexibility. Your feedback is appreciated!

**Comment by naNEQ** [comment]
I'll definitely give it a try next time! Thanks @LokleLama for this.
