### ISSUE TITLE
`west flash -r nrfjprog --erase --softreset` does not work on STM32 devices

### ISSUE THREAD

**Issue by glenn-andrews** [circuitdojo/zephyr-tools#4]
https://github.com/circuitdojo/zephyr-tools/blob/8a22128bbe72dfb6f95d95214d379600f8b26f48/src/extension.ts#L1403

What happens if this is changed to just `west flash` and let West decide on the correct runner to use?

**Comment by jaredwolff** [comment]
I think that may be OK. I'll have to experiment with it. Does that change work for you with the STM32?

**Comment by glenn-andrews** [comment]
I have no clue. I don't know how to rebuild and install a standalone extension. Are there build instructions somewhere?

If you can build it and provide instructions for installing a standalone extension on my Windows PC, I'll be happy to test it out for you.

**Comment by LokleLama** [comment]
there is a pull request that should help: https://github.com/circuitdojo/zephyr-tools/pull/7

**Comment by jaredwolff** [comment]
@glenn-andrews you now should be able to customize the runner you want to use for your project. You can run `Zephyr Tools: Change Runner` to select a runner and also add any extra arguments. You can see the commit here: #17

**Comment by glenn-andrews** [comment]
Thank you! Very helpful!
