### ISSUE TITLE
How do you use this extension

### ISSUE THREAD

**Issue by JerryDennisEasley** [circuitdojo/zephyr-tools#5]
I don't see any documentation about how to use this extension; do I need to enter command in the terminal?

**Comment by jaredwolff** [comment]
Hey @JerryDennisEasley 

You can refer to the getting started for the [nRF9160 Feather here.](https://docs.circuitdojo.com/nrf9160-getting-started.html) Your mileage may vary as it's not currently developed for anything other than Nordic parts.

You may want to check out my videos on it as well: https://www.youtube.com/live/KkYwstA3cWM?si=UJCeuzv5PlAk4ZGb&t=448

I hope that helps!
