### ISSUE TITLE
`app_update.bin` is not getting generated by `west build` 

### ISSUE THREAD

**Issue by maxkraft7** [circuitdojo/zephyr-tools#6]
I recently bought a NRF9160 feather. I'm currently stuck [here](https://docs.circuitdojo.com/nrf9160-example-code.html#:~:text=Then%2C%20load%20using%20the%20Zephyr%20Tools%3A%20Load%20via%20Bootloader%20task) at loading the file into the bootloader. 

When I run `west build -b circuitdojo_feather_nrf9160_ns` via the Zephyr Tools `build`-command a `app_update.bin` is not getting generated for some reason. I tried building this [this ](https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/tree/v2.4.x/samples/blinky) very basic blinky code. 

But `west flash -r nrfjprog --erase --softreset` isn't getting executed since it is looking for that file first. Then [this](https://github.com/circuitdojo/zephyr-tools/blob/main/src/extension.ts#L1273) warning of the extension triggers. 

This is the output of `west build` from the zephyr tools:
```
Executing task: west build -b circuitdojo_feather_nrf9160_ns 

[0/16] Performing build step for 'tfm'
[42/47] Linking C executable bin\tfm_s.axf
Memory region         Used Size  Region Size  %age Used
           FLASH:      129376 B       254 KB     49.74%
             RAM:       50296 B        88 KB     55.81%
[47/47] Generating tfm_s_signed.bin
image.py: sign the payload
[2/2] cmd.exe /C "cd /D C:\Users\max\Desktop\zephyrproject\zephyr\samples\blin...max/Desktop/zephyrproject/zephyr/samples/blinky_nrfed/build/zephyr/zephyr.elf"
```

Is there anything suspicious? What could be the reason that this file isn't there???

**Comment by jaredwolff** [comment]
Looks like you're not using the [NFED samples](https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers) but the Zephyr ones. You're missing: `CONFIG_BOOTLOADER_MCUBOOT=y`. Looks like you have an unconventional setup. I recommend the [Getting Started](https://docs.circuitdojo.com/nrf9160-getting-started.html) for setting up your project.

Feel free to post any other questions through your journey on the [community forum](https://community.circuitdojo.com/). I don't monitor Github very often.
